import {propertyTools,stages} from './product-ui.js';
import {icon} from './icons.js';
import {e,label,reviewLabel,num,euro, amount,stamp,relative,safeUrl,strategyTags,discount,selectOptions,activeRun,tone} from './utils.js';
import {notice,badge} from './ui.js';
const closeButton = '<button type="button" class="icon-button modal-close" data-action="close-modal" aria-label="Chiudi finestra">'+icon('close')+'</button>';
export function modalFrame(title, subtitle, body, cls='') {
  return `<dialog class="modal ${cls}" aria-labelledby="modal-title"><div class="modal-header"><div><div class="eyebrow">VEDRA WORKSPACE</div><h2 id="modal-title">${e(title)}</h2>${subtitle?`<p>${e(subtitle)}</p>`:''}</div>${closeButton}</div>${body}</dialog>`;
}
const formError = '<div class="form-error" id="modal-error" role="alert"></div>';
const footer = (text, iconName='check') => `<div class="modal-form-footer"><button type="button" class="btn" data-action="close-modal">Annulla</button><button type="submit" class="btn primary">${icon(iconName)} ${text}</button></div>`;
const types = ['residential','office','commercial','logistics','land','hospitality'];
const strategies = ['value_add','core_plus','development','conversion'];

export function agentDialog(s, agent) {
  const a=agent || {name:'',city:'Milano',criteria:{max_price:1500000,min_surface:100,max_listings:30,property_types:[],strategies:[],include_auctions:true},source_ids:[],runtime:'local',interval_minutes:0,active:true};
  const sources=s.data.sources;
  const readOnly=s.user.role==='viewer';
  return modalFrame(agent?'Configura agente':'Il tuo prossimo agente.','Una ricerca persistente, con criteri espliciti e fonti selezionate.',`<form id="agent-form" data-id="${e(agent?.id||'')}" class="modal-form"><fieldset ${readOnly?'disabled':''}>
    <div class="form-grid"><label class="span-2">Nome della ricerca<input name="name" value="${e(a.name)}" placeholder="es. Milano · Value Add" required minlength="2" maxlength="100"></label><label>Comune<input name="city" value="${e(a.city)}" placeholder="Milano" required minlength="2" maxlength="100" list="cities"><datalist id="cities"><option>Milano</option><option>Monza</option><option>Como</option></datalist></label><label>Frequenza<select name="interval_minutes">${selectOptions([[0,'Solo avvio manuale'],[15,'Ogni 15 minuti'],[30,'Ogni 30 minuti'],[60,'Ogni ora'],[360,'Ogni 6 ore'],[1440,'Ogni giorno'],[10080,'Ogni settimana']],a.interval_minutes)}</select></label><label>Budget minimo (€)<input name="min_price" type="number" min="0" max="1000000000" step="any" value="${a.criteria.min_price??0}" required></label><label>Budget massimo (€)<input name="max_price" type="number" min="1" max="1000000000" step="any" value="${a.criteria.max_price}" required></label><label>Superficie minima (m²)<input name="min_surface" type="number" min="0" step="any" value="${a.criteria.min_surface}" required></label><label>Superficie massima (opzionale)<input name="max_surface" type="number" min="1" step="any" value="${a.criteria.max_surface??''}" placeholder="Nessun massimo"></label><label>Sconto minimo sul benchmark (%)<input name="min_discount" type="number" min="0" max="100" step="any" value="${a.criteria.min_discount??''}" placeholder="Nessuna soglia"></label></div>
    <div class="field-group"><label>Tipologie <span class="muted">· nessuna selezione = tutte</span></label><div class="choice-chips">${types.map(x=>`<label class="choice-chip"><input type="checkbox" name="property_types" value="${x}" ${a.criteria.property_types.includes(x)?'checked':''}><span>${label(x)}</span></label>`).join('')}</div></div>
    <div class="field-group"><label>Strategie <span class="muted">· basate su evidenze testuali</span></label><div class="choice-chips">${strategies.map(x=>`<label class="choice-chip"><input type="checkbox" name="strategies" value="${x}" ${a.criteria.strategies.includes(x)?'checked':''}><span>${label(x)}</span></label>`).join('')}</div></div>
    <div class="field-group"><label>Fonti da monitorare</label><div class="source-choices">${sources.length?sources.map(src=>`<label class="source-choice"><input type="checkbox" name="source_ids" value="${e(src.id)}" ${a.source_ids.includes(src.id)?'checked':''} ${!src.enabled?'disabled':''}><span>${icon('layers')}</span><div><strong>${e(src.name)}</strong><small>${e(src.domain||'File importati')} ${!src.enabled?'· disabilitata':''}</small></div></label>`).join(''):'<p class="muted">Collega prima una fonte o importa un campione nella sezione Fonti.</p>'}</div></div>
    <div class="runtime-choice"><label>Runtime<select name="runtime">${selectOptions([['local','Regole locali · nessun LLM'],...((s.data.runtime.hermes_configured||a.runtime==='hermes')?[['hermes','Hermes · MCP ristretto']]:[]),...((s.data.runtime.ai_configured||a.runtime==='llm')?[['llm','AI verticale · modello configurato']]:[])],a.runtime)}</select></label><label>Massimo annunci / fonte / run<input name="max_listings" type="number" min="1" max="100" value="${a.criteria.max_listings}" required></label></div>
    <div class="checkbox-row"><label><input type="checkbox" name="include_auctions" ${a.criteria.include_auctions?'checked':''}> Includi aste</label><label><input type="checkbox" name="active" ${a.active?'checked':''}> Agente attivo</label></div>
    ${notice('Il filtro sullo sconto esclude gli asset senza benchmark compatibile. Pausa sospende gli avvii futuri, non una run già in corso.')}
    ${formError}${readOnly?'':footer(agent?'Salva configurazione':'Crea agente','plus')}</fieldset></form>`,'medium-modal');
}

export function sourceDialog(source) {
  const s=source||{name:'',domain:'',permission_note:'',config:{search_url:'',listing_selector:'a.property-link',listing_url_pattern:'/immobili/',next_selector:'a[rel="next"]',max_pages:2,render_js:false,fields:{price:'.price',surface:'.surface',city:'.city',zone:'.zone',property_type:'.asset-type',condition:'.condition',area_basis:'.area-basis',transaction_type:'.transaction'}}};
  return modalFrame(source?'Configura fonte HTML':'Una nuova fonte di dati.','Connettore generico, da verificare sulla fonte autorizzata.',`<form id="source-form" data-id="${e(source?.id||'')}" class="modal-form">
    ${notice('Aggiungi il dominio anche a <code>LIVE_ALLOWED_DOMAINS</code> nel server. La conferma qui sotto registra il permesso dichiarato, non sostituisce una verifica dei diritti.','warning')}
    <div class="form-grid"><label>Nome fonte<input name="name" required minlength="2" maxlength="100" value="${e(s.name)}" placeholder="Catalogo agenzia partner"></label><label>Dominio esatto<input name="domain" required value="${e(s.domain)}" placeholder="www.agenzia-partner.it"></label><label class="span-2">URL della ricerca<input name="search_url" required value="${e(s.config.search_url)}" placeholder="https://www.agenzia-partner.it/vendita/{city}/"><small><code>{city}</code> viene sostituito con il comune dell’agente in minuscolo.</small></label><label>Comune per il test fonte<input name="probe_city" maxlength="120" value="${e(s.config.probe_city||'')}" placeholder="Richiesto se URL contiene {city}"></label><label>Selettore link agli annunci<input name="listing_selector" required value="${e(s.config.listing_selector)}" placeholder="a.property-link"></label><label>Filtro percorso URL <span class="muted">· letterale</span><input name="listing_url_pattern" value="${e(s.config.listing_url_pattern)}" placeholder="/immobili/"></label><label>Selettore pagina successiva<input name="next_selector" value="${e(s.config.next_selector)}" placeholder='a[rel="next"]'></label><label>Scoperta URL<select name="discovery_mode">${selectOptions([["links","Link HTML"],["sitemap","Sitemap XML URL"]],s.config.discovery_mode||"links")}</select></label><label>Rileggi dettagli dopo (ore)<input name="detail_refresh_hours" type="number" min="1" max="720" value="${s.config.detail_refresh_hours||24}"></label><label>Massimo pagine di ricerca<input name="max_pages" type="number" min="1" max="5" value="${s.config.max_pages}" required></label></div>
    <label>Selettori dei campi · JSON<textarea name="fields" class="code-input" rows="9" spellcheck="false">${e(JSON.stringify(s.config.fields,null,2))}</textarea><small>Il parser prova prima JSON-LD. Questi selettori possono integrare o correggere i valori.</small></label>
    <label class="checkbox-label"><input type="checkbox" name="render_js" ${s.config.render_js?'checked':''}> Usa Chromium / Playwright (richiede abilitazione server)</label>
    <label>Nota sul permesso di acquisizione e riuso<textarea name="permission_note" rows="3" required minlength="10" maxlength="2000" placeholder="Riferimento all’accordo, dati autorizzati, titolare e limiti di utilizzo.">${e(s.permission_note)}</textarea></label><label class="checkbox-label"><input type="checkbox" name="permission_confirmed" required ${source?'checked':''}> Confermo di aver verificato l’autorizzazione all’accesso automatizzato e al riuso di questi dati.</label>
    ${formError}${footer(source?'Salva fonte':'Crea fonte','layers')}</form>`,'medium-modal');
}

export function importDialog(s) {
  return modalFrame('Dai file alle opportunità.','Dati verificabili, con la provenienza originale.',`<form id="import-form" class="modal-form">
    <div class="form-grid"><label>Tipo di importazione<select name="kind" id="import-kind">${selectOptions([['csv','CSV immobili'],['html','HTML singolo annuncio'],['benchmarks','CSV benchmark']])}</select></label></div>
    <div class="upload-zone"><span>${icon('upload')}</span><strong>Seleziona il file</strong><p>CSV o HTML UTF-8 · massimo 4 MB</p><input id="import-file" name="file" type="file" accept=".csv,.html,.htm,.txt,text/csv,text/html" aria-label="File da importare"><div id="file-name" class="file-name"></div></div>
    <details class="paste-details"><summary>Oppure incolla il contenuto</summary><textarea name="content" rows="7" class="code-input" placeholder="title,price,surface,city,…"></textarea></details>
    <label>URL originale <span class="muted">· obbligatorio per HTML</span><input name="source_url" type="url" placeholder="https://fonte-autorizzata.it/immobile/123"></label>
    ${notice('Per gli immobili: <code>title,price,surface,city,zone,property_type,condition,area_basis,currency,transaction_type,url,description</code>. Per i benchmark usa il tracciato CSV; OMI non viene scaricato automaticamente.')}
    <div class="template-links"><a href="/public/examples/properties.csv" download>${icon('download')} Tracciato immobili</a><a href="/public/examples/benchmarks.csv" download>${icon('download')} Tracciato benchmark</a></div>
    <label class="checkbox-label"><input type="checkbox" name="permission_confirmed" required> Ho i diritti di utilizzare i dati e confermo la provenienza dei dati.</label>${formError}${footer('Importa e normalizza','upload')}
    </form>`,'medium-modal');
}

export function propertyDialog(s,p) {
  const editor=s.user.role!=='viewer', sourceUrl=safeUrl(p.url);
  const missing=p.missing_fields || [];
  const factRows=[['Prezzo richiesto',amount(p.price,p.currency)],['Superficie',p.surface==null?'Non disponibile':`${num(p.surface)} m²`],['Prezzo al m²',amount(p.price_sqm,p.currency)],['Tipo di superficie',p.area_basis==='commercial'?'Commerciale':label(p.area_basis)],['Tipologia',label(p.property_type)],['Stato manutentivo',label(p.condition)],['Operazione',label(p.transaction_type)],['Indirizzo',p.address||'Non disponibile'],['Micro-zona',p.zone||'Non disponibile'],['Locali',num(p.rooms)],['Bagni',num(p.bathrooms)],['Procedura',p.is_auction?'Asta':'Non indicata come asta']];
  const benchmark=p.benchmark;
  return `<dialog class="modal property-drawer" aria-labelledby="modal-title"><div class="drawer-top"><div class="drawer-breadcrumb">${icon('building')} SCHEDA IMMOBILE <span>/</span> ${e(p.id.slice(0,8))}</div>${closeButton}</div>
    <div class="drawer-content"><div class="property-title-row"><span class="eyebrow">${e(p.city)} · ${e(p.zone || 'ZONA NON DISPONIBILE')}</span><span class="badge neutral">DATO ACQUISITO</span></div><h1 id="modal-title">${e(p.title)}</h1><div class="drawer-subtitle">${icon('pin')} ${e(p.address||'Indirizzo non disponibile')} <span>·</span> ${e(label(p.property_type))}</div>
    <div class="deal-actions"><button class="btn ${p.starred?'starred':''}" data-action="detail-star" data-id="${e(p.id)}" ${editor?'':'disabled'}>${icon('star')} ${p.starred?'Nei preferiti':'Salva'}</button><label class="review-select"><span class="sr-only">Stato revisione</span><select data-review="${e(p.id)}" ${editor?'':'disabled'}>${selectOptions(stages.map(x=>[x,reviewLabel(x)]),p.review_status)}</select></label><a class="btn" href="/api/properties/${e(p.id)}/memo.docx">${icon('document')} Scheda Word</a>${sourceUrl?`<a class="btn" href="${sourceUrl}" target="_blank" rel="noopener noreferrer">Fonte ${icon('upRight')}</a>`:''}</div>
    ${propertyTools(s,p)}
    <div class="deal-hero"><div class="deal-value"><span>PREZZO RICHIESTO</span><strong>${amount(p.price,p.currency)}</strong><p>${num(p.surface)} m² <span>·</span> ${amount(p.price_sqm,p.currency)} / m²</p></div><div class="deal-score"><div class="score-ring ${p.score==null?'no-score':''}" style="--score:${p.score??0}"><span>${p.score==null?'n.d.':num(p.score)}<small>${p.score==null?'':'/ 100'}</small></span></div><div><strong>Score di approfondimento</strong><span>Regole trasparenti, non probabilità di profitto.</span>${discount(p)}</div></div></div>
    <section class="detail-section"><div class="section-title"><h2>La lettura dell’asset</h2><span class="runtime-label ${p.analysis.engine==='hermes'?'hermes':''}">${icon(p.analysis.engine==='hermes'?'spark':'code')}${p.analysis.engine==='hermes'?'Hermes · evidenze validate':p.analysis.engine==='llm'?'AI · '+e(p.analysis.model||'modello configurato'):'Regole locali · nessuna AI'}</span></div><p class="asset-summary">${e(p.analysis.summary||p.description||'Descrizione non disponibile.')}</p><div class="evidence-strategies">${(p.analysis.strategies||[]).map(x=>`<div class="strategy-evidence"><span class="strategy ${e(x.strategy)}">${e(label(x.strategy))}</span><blockquote>“${e(x.evidence)}”</blockquote><small>Evidenza testuale nell’annuncio · non verifica tecnica</small></div>`).join('') || '<p class="muted">Nessuna strategia supportata dalle evidenze disponibili.</p>'}</div>${(p.analysis.caveats||[]).map(c=>`<p class="caveat">${icon('info')}${e(c)}</p>`).join('')}</section>
    <section class="detail-section"><div class="section-title"><h2>Prezzo, riferimento e metodo</h2><span class="quiet-pill">Calcoli deterministici</span></div>${benchmark?`<div class="benchmark-box"><div><span>Range di riferimento / m²</span><strong>${euro(benchmark.min_sqm)} <span>–</span> ${euro(benchmark.max_sqm)}</strong><small>${e(benchmark.source_label)} · ${e(benchmark.period)}</small></div><div><span>Scostamento dal punto medio</span><strong>${discount(p)}</strong><small>${e(benchmark.zone)} · ${e(label(benchmark.property_type))}</small></div></div><div class="score-explanation">${(p.score_breakdown||[]).map(b=>`<div><span>${e(b.label)}<small><code>${e(b.formula)}</code></small></span><strong>${num(b.points,1)} <small>/ ${b.max}</small></strong></div>`).join('')}</div><p class="small muted">Confronto limitato a stato e base di superficie compatibili. Non certifica sconto, margine, cambio d’uso o valore di rivendita. ${safeUrl(benchmark.source_url)?`<a href="${safeUrl(benchmark.source_url)}" target="_blank" rel="noopener noreferrer">Fonte del benchmark ${icon('upRight')}</a>`:''}</p>`:notice('Nessun benchmark compatibile disponibile: <strong>score e sconto rimangono non disponibili</strong>. Non usiamo una media generica di città o valori inventati.','warning')}</section>
    <section class="detail-section"><div class="section-title"><h2>I dati acquisiti</h2><span class="quiet-pill">Completezza ${num(p.completeness)}%</span></div><dl class="facts-grid">${factRows.map(([k,v])=>`<div><dt>${e(k)}</dt><dd>${e(v)}</dd></div>`).join('')}</dl>${missing.length?`<div class="missing-fields">${icon('info')} Campi mancanti: ${missing.map(label).map(e).join(', ')}.</div>`:''}<details class="source-evidence"><summary>${icon('document')} Provenienza campo per campo</summary><div class="table-scroll"><table class="evidence-table"><thead><tr><th>CAMPO</th><th>VALORE</th><th>METODO</th></tr></thead><tbody>${Object.entries(p.evidence).map(([k,v])=>`<tr><td>${e(label(k))}</td><td>${e(typeof v.value==='object'?JSON.stringify(v.value):v.value)}</td><td><code>${e(v.method)}</code></td></tr>`).join('')}</tbody></table></div><p><a class="btn small-btn" href="/api/properties/${e(p.id)}/snapshot">${icon('download')} Snapshot testuale originale</a></p></details></section>
    <section class="detail-section"><div class="section-title"><h2>Storico osservato</h2><button class="btn small-btn" data-action="property-history" data-id="${e(p.id)}">${icon('clock')} Variazioni dei campi</button><span class="quiet-pill">${num(p.observations.length)} osservazioni</span></div><p class="small muted">Prima rilevazione ${stamp(p.first_seen,true)}. Non è la data di pubblicazione. Memorizziamo una nuova osservazione quando cambia il contenuto. Importi storici grezzi: la valuta originaria è nello snapshot.</p><div class="price-history">${p.observations.slice(-12).reverse().map(o=>`<div><span class="history-dot"></span><time>${stamp(o.observed_at,true)}</time><strong>${num(o.price)}</strong><code>${e(o.parser_version)}</code></div>`).join('')}</div></section>
    ${p.screenings.length?`<section class="detail-section"><div class="section-title"><h2>Screening delle ricerche</h2></div>${p.screenings.map(a=>`<div class="screening-item"><span>${e(a.name)}</span>${badge(a.fit?'Nei criteri':'Fuori criteri',a.fit?'success':'neutral')}${a.fit_reasons.length?`<p>${a.fit_reasons.map(e).join(' · ')}</p>`:''}</div>`).join('')}</section>`:''}
    <section class="detail-section"><div class="section-title"><h2>Note del team</h2><span class="quiet-pill">Revisione umana</span></div>${editor?`<form id="note-form" data-id="${e(p.id)}"><label class="sr-only" for="note-body">Aggiungi una nota</label><textarea name="body" id="note-body" rows="3" maxlength="4000" required placeholder="Cosa merita una verifica? Aggiungi una nota per il team."></textarea><div class="note-submit"><div id="modal-error" class="form-error" role="alert"></div><button class="btn primary small-btn" type="submit">${icon('plus')} Aggiungi nota</button></div></form>`:''}<div class="notes-list">${p.notes.map(n=>`<article><div><strong>${e(n.author)}</strong><time>${stamp(n.created_at)}</time></div><p>${e(n.body)}</p></article>`).join('') || '<p class="muted small">Ancora nessuna nota.</p>'}</div></section>
    <div class="detail-provenance">${icon('layers')}<span>${e(p.source_name)}<small>Ultima acquisizione ${stamp(p.last_seen,true)} · ${num(p.images.length)} URL immagine rilevati; non scaricati dal browser cliente.</small></span></div></div></dialog>`;
}

export function runContent(run) {
  return `<div class="run-meta">${badge(label(run.status),tone(run.status))}<span class="runtime-label">${icon(run.runtime==='hermes'?'spark':'code')} ${run.runtime==='hermes'?'Hermes':run.runtime==='llm'?'AI verticale':'Regole locali'}</span><span class="muted small">${e(run.id.slice(0,8))} </span>${activeRun(run)?`<button class="btn small-btn danger-outline" data-action="cancel-run" data-id="${e(run.id)}">${icon('stop')} Annulla run</button>`:''}</div><div class="run-stat-grid">${[['Acquisiti',run.stats.processed],['Nuovi',run.stats.new],['Modificati',run.stats.changed],['Errori',run.stats.errors]].map(([k,v])=>`<div><strong>${num(v||0)}</strong><span>${k}</span></div>`).join('')}</div>${run.error?notice(e(run.error),'warning'):''}<div class="run-timeline">${run.events.length?run.events.map(ev=>`<div class="timeline-event ${e(ev.level)}"><span class="timeline-icon">${icon(ev.level==='error'?'warning':ev.level==='warning'?'info':'check')}</span><div><span class="event-step">${e(ev.step)} <time>${new Date(ev.time).toLocaleTimeString('it-IT')}</time></span><p>${e(ev.message)}</p></div></div>`).join(''):'<div class="empty-state compact"><span class="spinner"></span><p>Run in coda. Il worker la prenderà in carico.</p></div>'}</div><div class="run-footer"><span>Avvio ${stamp(run.created_at,true)}</span><span>${run.finished_at?`Fine ${stamp(run.finished_at,true)}`:'In attesa di conclusione'}</span></div>`;
}
export function runDialog(run) {
  return modalFrame(run.agent_name,'Registro di esecuzione persistente. I contatori riflettono i risultati effettivi.',`<div class="modal-body" id="run-content">${runContent(run)}</div>`,'medium-modal');
}
export function compareDialog(properties) {
  const rows=[['Prezzo',p=>amount(p.price,p.currency)],['Superficie',p=>num(p.surface)+' m²'],['Prezzo al m²',p=>amount(p.price_sqm,p.currency)],['Score',p=>p.score==null?'Non disponibile':num(p.score)+'/100'],['Delta zona',p=>p.discount==null?'Non disponibile':num(-p.discount,1)+'%'],['Tipologia',p=>label(p.property_type)],['Stato',p=>label(p.condition)],['Strategie',p=>(p.analysis.strategies||[]).map(x=>label(x.strategy)).join(', ')||'Non disponibili'],['Completezza',p=>num(p.completeness)+'%'],['Benchmark',p=>p.benchmark?.source_label||'Non disponibile'],['Periodo',p=>p.benchmark?.period||'Non disponibile'],['Fonte',p=>p.source_name],['Provenienza',p=>'Acquisizione / importazione']];
  return modalFrame('Metti a confronto.','Confronto del campione selezionato: non rende omogenei asset diversi.',`<div class="modal-body"><div class="table-scroll"><table class="compare-table"><thead><tr><th>INDICATORE</th>${properties.map(p=>`<th><span class="compare-city">${e(p.city)} · ${e(p.zone)}</span><button data-action="property" data-id="${e(p.id)}">${e(p.title)}</button></th>`).join('')}</tr></thead><tbody>${rows.map(([name,fn])=>`<tr><th>${e(name)}</th>${properties.map(p=>`<td>${e(fn(p))}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div>`,'wide-modal');
}
export function userDialog() {
  return modalFrame('Aggiungi una persona.','Account locale al workspace. Comunica la password iniziale attraverso un canale sicuro.',`<form id="user-form" class="modal-form"><div class="form-grid"><label class="span-2">Nome<input name="name" required minlength="2" maxlength="100" autocomplete="off"></label><label class="span-2">Email<input name="email" type="email" required autocomplete="off"></label><label>Ruolo<select name="role">${selectOptions([['viewer','Sola lettura'],['analyst','Analista'],['admin','Amministratore']])}</select></label><label>Password iniziale<input name="password" type="password" minlength="12" maxlength="256" autocomplete="new-password" required></label></div>${notice('Gli analisti gestiscono ricerche, revisioni e note. Solo gli amministratori configurano fonti, importazioni e utenti.')}${formError}${footer('Crea account','plus')}</form>`);
}
