import {comparisonContent} from './comparison-ui.js';
import {historyPreview} from './history-ui.js';
import {runContent} from './run-ui.js';
import {decisionSection} from './decision-ui.js';
import {priceLadder,signalFacts} from './signals-ui.js';
import {marketContext} from './market-ui.js';
import {propertyTools,stages} from './product-ui.js';
import {icon} from './icons.js';
import {e,label,reviewLabel,num,euro, amount,stamp,safeUrl,discount,selectOptions} from './utils.js';
import {notice,badge} from './ui.js';
const closeButton = '<button type="button" class="icon-button modal-close" data-action="close-modal" aria-label="Chiudi finestra">'+icon('close')+'</button>';
export function modalFrame(title, subtitle, body, cls='') {
  return `<dialog class="modal ${cls}" aria-labelledby="modal-title"><div class="modal-header"><div><h2 id="modal-title">${e(title)}</h2>${subtitle?`<p>${e(subtitle)}</p>`:''}</div>${closeButton}</div>${body}</dialog>`;
}
const formError = '<div class="form-error" id="modal-error" role="alert"></div>';
const footer = (text, iconName='check') => `<div class="modal-form-footer"><button type="button" class="btn" data-action="close-modal">Annulla</button><button type="submit" class="btn primary">${icon(iconName)} ${text}</button></div>`;
const types = ['residential','office','commercial','logistics','land','hospitality'];
const strategies = ['value_add','core_plus','development','conversion'];

export function agentDialog(s, agent, copy=false) {
  const a=agent || {name:'',city:'Milano',criteria:{opportunity_only:true,contact_policy:'prefer_direct',max_price:1500000,min_surface:100,max_listings:30,property_types:[],strategies:[],include_auctions:true},source_ids:[],runtime:s.data.runtime.ai_configured?'scout':'local',interval_minutes:360,active:true};
  const c=a.criteria,sources=s.data.sources,readOnly=s.user.role==='viewer';
  const advancedCount=(c.max_surface!=null?1:0)+(c.include_auctions?1:0);
  const instructions=!!(c.research_instructions||Object.keys(c.source_urls||{}).length);
  // A copy reuses every criterion but saves as a new search: no id, no revision.
  const id=copy?'':agent?.id||'';
  return modalFrame(copy?'Duplica ricerca':agent?'Configura ricerca':'Nuova ricerca','',`<form id="agent-form" data-id="${e(id)}" data-revision="${e(copy?'':agent?.revision||'')}" class="modal-form research-form"><fieldset ${readOnly?'disabled':''}>
    <section class="research-section" aria-labelledby="asset-heading"><h3 id="asset-heading"><span>1</span> Zona e budget</h3><div class="research-section-body">
      <div class="form-grid"><label>Nome<input name="name" value="${e(a.name)}" placeholder="Milano · Value Add" required minlength="2" maxlength="100"></label><label>Comune<input name="city" value="${e(a.city)}" placeholder="Milano" required minlength="2" maxlength="100"></label>
      <label class="span-2"><span class="field-caption">Zona o indirizzo <span class="optional-label">facoltativo</span></span><input name="location_query" value="${e(c.location_query||'')}" maxlength="100" placeholder="Argonne oppure viale Corsica"><small>Cerca queste parole negli annunci.</small></label>
      <label>Budget minimo (€)<input name="min_price" type="number" min="0" max="1000000000" step="any" value="${c.min_price??0}" required></label><label>Budget massimo (€)<input name="max_price" type="number" min="1" max="1000000000" step="any" value="${c.max_price}" required></label>
      <label>Superficie minima (m²)<input name="min_surface" type="number" min="0" step="any" value="${c.min_surface}" required></label><label>Sconto minimo sul benchmark (%)<input name="min_discount" type="number" min="0" max="100" step="any" value="${c.min_discount??''}" placeholder="Nessuna soglia"></label></div>
    </div></section>
    <section class="research-section" aria-labelledby="criteria-heading"><h3 id="criteria-heading"><span>2</span> Criteri</h3><div class="research-section-body">
      <label>Criteri personalizzati<textarea aria-label="Criteri personalizzati" name="custom_prompt" maxlength="6000" rows="4" placeholder="Un requisito per riga. Es.: cambio d’uso esplicitamente indicato nell’annuncio.">${e(c.custom_prompt||'')}</textarea><small>Ogni requisito deve avere evidenze nell’annuncio.</small></label>
      <div class="field-group"><label>Tipologie <span class="optional-label">nessuna = tutte</span></label><div class="choice-chips">${types.map(x=>`<label class="choice-chip"><input type="checkbox" name="property_types" value="${x}" ${c.property_types.includes(x)?'checked':''}><span>${label(x)}</span></label>`).join('')}</div></div>
      <div class="field-group"><label>Strategie <span class="optional-label">con evidenze testuali</span></label><div class="choice-chips">${strategies.map(x=>`<label class="choice-chip"><input type="checkbox" name="strategies" value="${x}" ${c.strategies.includes(x)?'checked':''}><span>${label(x)}</span></label>`).join('')}</div></div>
      <label class="check-line"><input type="checkbox" name="opportunity_only" ${c.opportunity_only?'checked':''}> Solo sotto benchmark</label><p class="field-hint">Esclude prezzi in linea e confronti mancanti.</p>
      <label>Contatto cercato<select name="contact_policy" aria-label="Contatto cercato">${selectOptions([['prefer_direct','Dai precedenza al contatto diretto'],['require_direct','Solo diretto dichiarato con recapito'],['any','Qualsiasi inserzionista']],c.contact_policy||'any')}</select><small>Proprietà o mandato esclusivo dichiarati, da confermare.</small></label>
      <details class="research-settings"><summary>Istruzioni per Scout<span class="setting-indicator" data-instruction-indicator ${instructions?'':'hidden'}>Configurate</span></summary><div class="disclosure-body"><label>Istruzioni di ricerca<textarea aria-label="Istruzioni di ricerca" name="research_instructions" rows="4" maxlength="6000" placeholder="Parti dal catalogo del broker, visita gli annunci selezionati e identifica chi li gestisce.">${e(c.research_instructions||'')}</textarea><small>Indica dove cercare e cosa controllare, nelle fonti collegate.</small></label>${sources.filter(src=>src.kind==='html').map(src=>`<label>Pagina da monitorare · ${e(src.name)}<input name="source_url_${e(src.id)}" type="url" maxlength="2000" value="${e(c.source_urls?.[src.id]||'')}" placeholder="${e(src.config.search_url||'')}"><small>Facoltativa, sul dominio della fonte selezionata.</small></label>`).join('')}</div></details>
      <details class="research-advanced"><summary>Superficie massima e aste<span class="setting-indicator" data-filter-indicator ${advancedCount?'':'hidden'}>${advancedCount} ${advancedCount===1?'selezionato':'selezionati'}</span></summary><div class="disclosure-body">
      <label>Superficie massima (opzionale)<input name="max_surface" type="number" min="1" step="any" value="${c.max_surface??''}" placeholder="Nessun massimo"></label><label class="check-line"><input type="checkbox" name="include_auctions" ${c.include_auctions?'checked':''}> Includi aste</label>
      </div></details>
    </div></section>
    <section class="research-section" aria-labelledby="research-heading"><h3 id="research-heading"><span>3</span> Ricerca</h3><div class="research-section-body">
      <div class="field-group" id="research-sources"><label>Fonti da monitorare</label><div class="source-choices">${sources.length?sources.map(src=>`<label class="source-choice"><input type="checkbox" name="source_ids" value="${e(src.id)}" ${a.source_ids.includes(src.id)?'checked':''} ${!src.enabled?'disabled':''}><span>${icon('layers')}</span><div><strong>${e(src.name)}</strong><small>${e(src.domain||'File importati')}${!src.enabled?' · disabilitata':''}</small></div></label>`).join(''):'<p class="muted">Nessuna fonte. <a href="#sources">Collega una fonte</a>.</p>'}</div></div>
      <div class="form-grid research-runtime-grid"><label>Motore<select name="runtime">${selectOptions([...((s.data.runtime.ai_configured||a.runtime==='scout')?[['scout','Scout · naviga i siti']]:[]),['local','Solo regole sull’archivio'],...((s.data.runtime.ai_configured||a.runtime==='llm')?[['llm','AI sull’archivio']]:[]),...((s.data.runtime.hermes_configured||a.runtime==='hermes')?[['hermes','Hermes (legacy)']]:[])],a.runtime)}</select></label><label>Frequenza<select name="interval_minutes">${selectOptions([[0,'Solo avvio manuale'],[15,'Ogni 15 minuti'],[30,'Ogni 30 minuti'],[60,'Ogni ora'],[360,'Ogni 6 ore'],[1440,'Ogni giorno'],[10080,'Ogni settimana']],a.interval_minutes)}</select></label><label>${c.online_discovery?'Nuovi annunci':'Annunci'} per fonte<input name="max_listings" type="number" min="1" max="100" value="${c.max_listings}" required></label></div>
      <div class="checkbox-row"><label data-hermes-only ${a.runtime==='hermes'?'':'hidden'}><input type="checkbox" name="online_discovery" ${c.online_discovery?'checked':''}> Ricerca online con Hermes</label><label><input type="checkbox" name="active" ${a.active?'checked':''}> Agente attivo</label></div>
      <details class="research-help"><summary>Come viene eseguita</summary><p>Scout apre le fonti web come una persona: sceglie annunci e sezioni seguendo le tue istruzioni e legge ogni scheda. I valori non scritti nella pagina restano vuoti. I siti che bloccano l’accesso automatico vengono segnalati, non aggirati. Gli altri motori rianalizzano l’archivio. La frequenza vale anche a browser chiuso.</p></details>
    </div></section>
    ${formError}<div class="research-save-conflict" hidden><button type="button" class="btn primary" data-action="reload-research">Rileggi ricerca</button></div>${readOnly?'':footer('Salva ricerca','check')}</fieldset></form>`,'medium-modal research-modal');
}

export function sourceDialog(source,presets=[]) {
  const s=source||{name:'',domain:'',permission_note:'',config:{search_url:'',listing_selector:'a.property-link',listing_url_pattern:'/immobili/',next_selector:'a[rel="next"]',max_pages:2,render_js:false,fields:{price:'.price',surface:'.surface',city:'.city',zone:'.zone',property_type:'.asset-type',condition:'.condition',area_basis:'.area-basis',transaction_type:'.transaction'}}};
  return modalFrame(source?'Configura fonte':'Collega fonte','',`<form id="source-form" data-id="${e(source?.id||'')}" class="modal-form">
    ${!source&&presets.length?`<label>Fonte pronta<select id="source-preset" aria-label="Portale" aria-describedby="preset-help"><option value="">Personalizzata</option>${[['agency','Reti di agenzie · Scout'],['portal','Portali · spesso bloccano l’accesso automatico']].map(([g,t])=>presets.some(p=>p.group===g)?`<optgroup label="${t}">${presets.map((p,i)=>p.group===g?`<option value="${i}">${e(p.name)}</option>`:'').join('')}</optgroup>`:'').join('')}${presets.map((p,i)=>!p.group?`<option value="${i}">${e(p.name)}</option>`:'').join('')}</select></label><p id="preset-help" class="small muted">Le agenzie pubblicano gli immobili di cui hanno il mandato. Usa Test per verificare l’accesso.</p>`:''}
    <div class="form-grid"><label>Nome fonte<input name="name" required minlength="2" maxlength="100" value="${e(s.name)}" placeholder="Catalogo agenzia"></label><label>Dominio<input name="domain" required value="${e(s.domain)}" placeholder="www.agenzia.it"></label><label class="span-2">URL della ricerca<input name="search_url" required value="${e(s.config.search_url)}" placeholder="https://www.agenzia.it/vendita/"><small>Per un altro comune, incolla la ricerca del portale.</small></label></div>
    <label class="checkbox-label"><input type="checkbox" name="browser_navigation" ${s.config.browser_navigation?'checked':''}> Apri le pagine nel browser</label>
    <details><summary>Impostazioni di acquisizione</summary><div class="form-grid">
    <label>Comune per il test<input name="probe_city" maxlength="120" value="${e(s.config.probe_city||'')}" placeholder="Se l’URL contiene {city}"></label><label>Rileggi dettagli dopo (ore)<input name="detail_refresh_hours" type="number" min="1" max="720" value="${s.config.detail_refresh_hours||24}"></label><label>Massimo pagine<input name="max_pages" type="number" min="1" max="5" value="${s.config.max_pages}" required></label><label>Scoperta URL<select name="discovery_mode">${selectOptions([["links","Link HTML"],["sitemap","Sitemap XML"]],s.config.discovery_mode||"links")}</select></label>
    <label>Selettore annunci<input name="listing_selector" required value="${e(s.config.listing_selector)}"></label><label>Filtro percorso<input name="listing_url_pattern" value="${e(s.config.listing_url_pattern)}"></label><label>Selettore pagina successiva<input name="next_selector" value="${e(s.config.next_selector)}"></label></div>
    <label>Selettori dei campi · JSON<textarea name="fields" class="code-input" rows="5" spellcheck="false">${e(JSON.stringify(s.config.fields,null,2))}</textarea></label>
    <label class="checkbox-label"><input type="checkbox" name="render_js" ${s.config.render_js?'checked':''}> Rendering JavaScript</label><label class="checkbox-label"><input type="checkbox" name="retain_images" ${s.config.retain_images?'checked':''}> Conserva riferimenti alle foto</label><label class="checkbox-label"><input type="checkbox" name="facts_only" ${s.config.retain_raw_html===false?'checked':''}> Conserva solo i dati estratti</label><p class="small muted">Il dominio deve essere abilitato sul server. <code>{city}</code> usa il comune dell’agente in minuscolo.</p></details>
    <label>Permesso di accesso e riuso<textarea name="permission_note" rows="2" required minlength="10" maxlength="2000" placeholder="Accordo, dati autorizzati e limiti di utilizzo.">${e(s.permission_note)}</textarea></label><label class="checkbox-label"><input type="checkbox" name="permission_confirmed" required ${source?'checked':''}> Confermo l’autorizzazione all’accesso automatizzato e al riuso.</label>
    ${formError}${footer(source?'Salva fonte':'Crea fonte','layers')}</form>`,'medium-modal');
}

export function sourceProbeDialog(result) {
  const sample=result.sample;
  const raw=result.notice||'Verifica non riuscita.';
  const reason=/HTTP 403/.test(raw)?'Il portale rifiuta l’accesso dal server (HTTP 403).':/BROWSER_ENABLED/.test(raw)?'Il browser del server non è attivo.':/allowlist/.test(raw)?'Il dominio deve essere abilitato sul server.':/Challenge/i.test(raw)?'Il portale richiede una verifica nel browser.':raw;
  return modalFrame(result.ok?'Fonte verificata':'Fonte non disponibile','',`<div class="modal-body">
    ${result.ok?`<div class="run-stat-grid"><div><strong>${num(result.links_found)}</strong><span>Link trovati</span></div><div><strong>1</strong><span>Annuncio verificato</span></div></div>${sample?`<p><strong>${e(sample.title)}</strong></p><p>${amount(sample.price,sample.currency)} · ${num(sample.surface)} m² · ${e(sample.city||'Comune mancante')}</p>`:''}${result.missing_fields?.length?`<p class="small muted">Da completare: ${result.missing_fields.map(label).map(e).join(', ')}.</p>`:''}<p class="small muted">Il test non importa annunci.</p>`:notice(e(reason),'warning')}
    <details><summary>Dettagli tecnici</summary><pre class="json-result">${e(JSON.stringify(result,null,2))}</pre></details>
    </div>`,'medium-modal');
}

export {importDialog} from './import-ui.js';

export function propertyDialog(s,p) {
  const editor=s.user.role!=='viewer', sourceUrl=safeUrl(p.url);
  const missing=p.missing_fields || [];
  const factRows=[['Prezzo richiesto',amount(p.price,p.currency)],['Superficie',p.surface==null?'Non disponibile':`${num(p.surface)} m²`],['Prezzo al m²',amount(p.price_sqm,p.currency)],['Tipo di superficie',p.area_basis==='commercial'?'Commerciale':label(p.area_basis)],['Tipologia',label(p.property_type)],['Stato manutentivo',label(p.condition)],['Operazione',label(p.transaction_type)],['Indirizzo',p.address||'Non disponibile'],['Micro-zona',p.zone||'Non disponibile'],['Locali',num(p.rooms)],['Bagni',num(p.bathrooms)],['Procedura',p.is_auction?'Asta':'Non indicata come asta']];
  const benchmark=p.benchmark, priority=p.priority||{score:0,factors:[],label:'Priorità di verifica'};
  const availability={sold:'Venduto',rented:'Affittato',withdrawn:'Ritirato',review:'Da verificare',unknown:'Da verificare',listed:'Pubblicato'}[p.availability]||'Da verificare';
  const closed=['sold','rented','withdrawn','review'].includes(p.availability);
  return `<dialog class="modal property-drawer" aria-labelledby="modal-title"><div class="drawer-top"><div class="drawer-breadcrumb">${icon('building')}<span>${e(p.source_name||'Immobile')}</span></div>${closeButton}</div>
    <div class="drawer-content"><div class="property-title-row"><span class="eyebrow">${[p.city,p.zone].filter(Boolean).map(e).join(' · ')||'Località da verificare'}</span>${badge(availability,closed?'warning':'neutral')}</div><h1 id="modal-title">${e(p.title)}</h1><div class="drawer-subtitle">${p.address?`${icon('pin')} ${e(p.address)} <span>·</span> `:''}${e(label(p.property_type))}${p.condition&&p.condition!=='unknown'?` <span>·</span> ${e(label(p.condition))}`:''}</div>
    ${closed?notice(`${e(availability)} · escluso dalle opportunità attive.`,'warning'):''}
    <div class="deal-hero"><div class="deal-value"><span>PREZZO RICHIESTO</span><strong>${amount(p.price,p.currency)}</strong><p>${num(p.surface)} m² <span>·</span> ${amount(p.price_sqm,p.currency)} / m²</p></div><div class="deal-score"><div class="score-ring ${closed?'no-score':''}" style="--score:${priority.score}"><span>${num(priority.score)}<small>/100</small></span></div><div><strong>${e(priority.label)}</strong><details class="priority-method"><summary>Come si calcola</summary><p>${e(priority.reason)}</p>${priority.factors.map(f=>`<div><span>${e(f.label)}</span><strong>${num(f.points,1)} / ${f.max}</strong></div>`).join('')}</details></div></div></div>
    <div class="deal-actions">
      <div class="review-actions" role="group" aria-label="Selezione immobile"><button class="btn ${p.starred?'starred':''}" data-action="detail-star" data-id="${e(p.id)}" ${editor?'':'disabled'}>${icon('star')} ${p.starred?'Nei preferiti':'Salva'}</button><label class="review-select"><span class="sr-only">Stato revisione</span><select data-review="${e(p.id)}" ${editor?'':'disabled'}>${selectOptions(stages.map(x=>[x,reviewLabel(x)]),p.review_status)}</select></label></div>
      <div class="export-actions" role="group" aria-label="Esporta scheda"><a class="btn primary" href="/api/properties/${e(p.id)}/memo.xlsx">${icon('download')} Excel</a><a class="btn" href="/api/properties/${e(p.id)}/memo.docx">${icon('document')} Word</a></div>
    </div>
    <div class="property-workspace-actions">${propertyTools(s,p)}${sourceUrl?`<a class="btn source-link" href="${sourceUrl}" target="_blank" rel="noopener noreferrer">Fonte ${icon('upRight')}</a>`:''}</div>
    ${valuation(p)}
    ${decisionSection(s,p)}
    ${fourReferences(p)}
    ${p.screenings.length?`<section class="detail-section"><div class="section-title"><h2>Criteri delle ricerche</h2></div>${p.screenings.map(a=>`<div class="screening-item"><span>${e(a.name)}</span>${badge(a.fit?'Nei criteri':'Fuori criteri',a.fit?'success':'neutral')}${qualitativeCheck(a)}${a.fit_reasons.some(r=>!a.custom_prompt||!r.startsWith('Criteri personalizzati'))?`<p>${a.fit_reasons.filter(r=>!a.custom_prompt||!r.startsWith('Criteri personalizzati')).map(e).join(' · ')}</p>`:''}</div>`).join('')}</section>`:''}
    ${p.images?.length?`<section class="detail-section"><h2>Foto</h2><div class="listing-gallery">${p.images.slice(0,6).map((_,i)=>`<img class="listing-photo" src="/api/properties/${encodeURIComponent(p.id)}/image?index=${i}" alt="Immagine ${i+1} dell’annuncio" loading="lazy" decoding="async">`).join('')}</div><p class="muted">${e(p.source_name)} · <a href="${sourceUrl}" target="_blank" rel="noopener noreferrer">Apri fonte</a></p></section>`:''}
    <section class="detail-section" ${closed||(!['hermes','llm'].includes(p.analysis.engine)&&!p.analysis.strategies?.length)?'hidden':''}><div class="section-title"><h2>Analisi</h2><span class="runtime-label ${p.analysis.engine==='hermes'?'hermes':''}">${icon(p.analysis.engine==='hermes'?'spark':'code')}${p.analysis.engine==='hermes'?'Hermes':p.analysis.engine==='llm'?'AI · '+e(p.analysis.model||'modello configurato'):'Regole'}</span></div>${['hermes','llm'].includes(p.analysis.engine)?`<p class="asset-summary">${e(p.analysis.summary||'')}</p>`:''}<details><summary>Evidenze e verifiche</summary><div class="evidence-strategies">${(p.analysis.strategies||[]).map(x=>`<div class="strategy-evidence"><span class="strategy ${e(x.strategy)}">${e(label(x.strategy))}</span><blockquote>“${e(x.evidence)}”</blockquote><small>Evidenza testuale nell’annuncio · non verifica tecnica</small></div>`).join('') || '<p class="muted">Nessuna strategia documentata.</p>'}</div>${(p.analysis.caveats||[]).map(c=>`<p class="caveat">${icon('info')}${e(c)}</p>`).join('')}</details></section>
    <section class="detail-section"><details><summary>Benchmark per lo screening</summary>${benchmark?`<div class="benchmark-box"><div><span>Range di riferimento / m²</span><strong>${euro(benchmark.min_sqm)} <span>–</span> ${euro(benchmark.max_sqm)}</strong><small>${e(benchmark.source_label)} · ${e(benchmark.period)}</small></div><div><span>Scostamento dal punto medio</span><strong>${discount(p)}</strong><small>${e(benchmark.zone)} · ${e(label(benchmark.property_type))}</small></div></div><div class="score-explanation">${(p.score_breakdown||[]).map(b=>`<div><span>${e(b.label)}<small><code>${e(b.formula)}</code></small></span><strong>${num(b.points,1)} <small>/ ${b.max}</small></strong></div>`).join('')}</div><p class="small muted">Confronto limitato a stato e base di superficie compatibili. Non certifica sconto, margine, cambio d’uso o valore di rivendita. ${safeUrl(benchmark.source_url)?`<a href="${safeUrl(benchmark.source_url)}" target="_blank" rel="noopener noreferrer">Fonte del benchmark ${icon('upRight')}</a>`:''}</p>`:'<p class="small muted">Nessun benchmark compatibile configurato.</p>'}</details></section>
    ${marketContext(p)}
    <section class="detail-section"><div class="section-title"><h2>Dati</h2><span class="quiet-pill">Completezza ${num(p.completeness)}%</span></div><dl class="facts-grid">${factRows.map(([k,v])=>`<div><dt>${e(k)}</dt><dd>${e(v)}</dd></div>`).join('')}</dl>${missing.length?`<div class="missing-fields">${icon('info')} Campi mancanti: ${missing.map(label).map(e).join(', ')}.</div>`:''}<details class="source-evidence"><summary>${icon('document')} Provenienza campo per campo</summary><div class="table-scroll"><table class="evidence-table"><thead><tr><th>CAMPO</th><th>VALORE</th><th>METODO</th></tr></thead><tbody>${Object.entries(p.evidence).filter(([,v])=>v?.method).map(([k,v])=>`<tr><td>${e(label(k))}</td><td>${e(typeof v.value==='object'?JSON.stringify(v.value):v.value)}</td><td><code>${e(v.method)}</code></td></tr>`).join('')}</tbody></table></div><p><a class="btn small-btn" href="/api/properties/${e(p.id)}/snapshot">${icon('download')} Snapshot testuale originale</a></p></details></section>
    ${historyPreview(p)}
    <section class="detail-section"><div class="section-title"><h2>Note del team</h2><span class="quiet-pill">Revisione umana</span></div>${editor?`<form id="note-form" data-id="${e(p.id)}"><label class="sr-only" for="note-body">Aggiungi una nota</label><textarea name="body" id="note-body" rows="3" maxlength="4000" required placeholder="Cosa merita una verifica? Aggiungi una nota per il team."></textarea><div class="note-submit"><div id="modal-error" class="form-error" role="alert"></div><button class="btn primary small-btn" type="submit">${icon('plus')} Aggiungi nota</button></div></form>`:''}<div class="notes-list">${p.notes.map(n=>`<article><div><strong>${e(n.author)}</strong><time>${stamp(n.created_at)}</time></div><p>${e(n.body)}</p></article>`).join('') || '<p class="muted small">Ancora nessuna nota.</p>'}</div></section>
    <div class="detail-provenance">${icon('layers')}<span>${e(p.source_name)}<small>Ultima acquisizione ${stamp(p.last_seen,true)}</small></span></div></div></dialog>`;
}

export function runDialog(run,canEdit=true) {
  return modalFrame(run.agent_name,'',`<div class="modal-body" id="run-content">${runContent(run,canEdit)}</div>`,'medium-modal run-modal');
}
export function compareDialog(properties) {
  return modalFrame('Confronto',`${properties.length} immobili selezionati`,comparisonContent(properties),'wide-modal comparison-modal');
}
export function userDialog() {
  return modalFrame('Nuovo utente','Accesso a questo workspace.',`<form id="user-form" class="modal-form"><div class="form-grid"><label class="span-2">Nome<input name="name" required minlength="2" maxlength="100" autocomplete="off"></label><label class="span-2">Email<input name="email" type="email" required autocomplete="off"></label><label>Ruolo<select name="role">${selectOptions([['viewer','Sola lettura'],['analyst','Analista'],['admin','Amministratore']])}</select></label><label>Password iniziale<input name="password" type="password" minlength="12" maxlength="256" autocomplete="new-password" required></label></div>${notice('Gli analisti gestiscono ricerche, revisioni e note. Solo gli amministratori configurano fonti, importazioni e utenti.')}${formError}${footer('Crea account','plus')}</form>`);
}

function valuation(p) {
  if(!p.signals)return '';
  return `<section class="valuation" aria-labelledby="valuation-title"><div class="valuation-head"><h2 id="valuation-title">Prezzo e mercato</h2></div>${priceLadder(p)}${signalFacts(p)}</section>`;
}

function fourReferences(p) {
  const refs=p.market_references;if(!refs)return '';
  return `<section class="detail-section market-decision-section"><details class="reference-samples" ${p.signals?'':'open'}><summary><h2>Riferimenti di mercato</h2><span class="setting-indicator">Campioni e metodo</span></summary><div class="reference-grid">${refs.groups.map(g=>`<article class="reference-card"><span>${e(g.label)}</span><strong class="${g.median_sqm==null?'reference-missing':''}">${g.median_sqm==null?'—':amount(g.median_sqm,p.currency)+'/m²'}</strong><small>${g.median_sqm==null?e(g.reason):`${num(g.count)} annunci · ${num(g.source_count??0)} ${g.source_count===1?'fonte':'fonti'}`}</small>${g.q1_sqm!=null?`<small>Fascia centrale: ${amount(g.q1_sqm,p.currency)}–${amount(g.q3_sqm,p.currency)}/m²</small>`:''}${g.asking_delta_pct!=null?`<small>Richiesta ${g.asking_delta_pct>0?'+':''}${num(g.asking_delta_pct,1)}% sulla mediana</small>`:''}${(g.warnings||[]).map(w=>`<small class="evidence-warning">${e(w)}</small>`).join('')}${g.items.length?`<details><summary>Vedi campione</summary><p class="small muted">${stamp(g.oldest_observed,true)} – ${stamp(g.newest_observed,true)} · Intervallo osservato</p>${g.items.map(x=>`<button class="plain-link" data-action="property" data-id="${e(x.id)}">${e(x.title)} · ${amount(x.price_sqm,p.currency)}/m²<small>${e(x.source)} · ${stamp(x.observed_at,true)}</small></button>`).join('')}</details>`:''}</article>`).join('')}<article class="reference-card omi-reference"><span>OMI</span>${refs.omi?.status==='available'&&!refs.omi?.stale&&refs.omi.rows?.length?`${refs.omi.rows.slice(0,2).map(r=>`<div class="omi-reference-row"><strong>${euro(r.min_sqm)}–${euro(r.max_sqm)}/m²</strong><small>${e(r.type)} · ${e(r.condition)} · ${r.area_basis==='gross'?'lorda':'netta'}</small></div>`).join('')}<small>${e(refs.omi.period)} · ${e(refs.omi.zone_code||'')} · riferimento di zona</small>${refs.omi.rows.length>2?`<small>${refs.omi.rows.length} fasce nella tabella OMI della scheda</small>`:''}`:`<strong class="reference-missing">—</strong><small>${e(refs.omi?.stale?'Periodo da aggiornare: '+refs.omi.period:refs.omi?.reason||'Quotazione di zona non disponibile')}</small>`}</article></div><details><summary>Come confrontiamo</summary><p class="small muted">${e(refs.method)} La fascia centrale contiene il 50% dei prezzi osservati, non è un intervallo di confidenza. Più fonti non significano necessariamente informazioni indipendenti.${refs.sample_limited?' Campione limitato ai 1.000 annunci più recenti.':''}</p></details></details></section>`;
}

function qualitativeCheck(a) {
  if(!a.custom_prompt)return '';
  const result=a.custom_assessment;
  const status={matched:'Coerente',not_matched:'Non coerente',uncertain:'Da verificare'};
  const checks=result?.checks?.length?result.checks:result?[{criterion:a.custom_prompt,...result}]:[];
  const matched=checks.filter(c=>c.status==='matched').length;
  const shownQuotes=new Set(checks.flatMap(c=>c.evidence||[]));
  const extra=[...new Set(result?.evidence||[])].filter(q=>!shownQuotes.has(q));
  return `<details class="qualitative-check"><summary>Criteri AI · ${status[result?.status]||'Da analizzare'}${checks.length?`<span class="setting-indicator">${num(matched)} / ${num(checks.length)} coerenti</span>`:''}</summary>
    ${checks.length?checks.map(c=>`<article class="criterion-result"><div class="criterion-heading"><strong>${e(c.criterion)}</strong>${badge(status[c.status]||'Da verificare',c.status==='matched'?'success':c.status==='not_matched'?'neutral':'warning')}</div><p>${e(c.reason)}</p>${c.evidence?.length?`<details class="criterion-evidence"><summary>Evidenze · ${num(new Set(c.evidence).size)}</summary>${[...new Set(c.evidence)].map(q=>`<blockquote>${e(q)}</blockquote>`).join('')}</details>`:''}</article>`).join(''):`<p class="preserve-lines">${e(a.custom_prompt)}</p><p>Esegui la ricerca per verificare questi criteri.</p>`}
    ${result?.checks?.length?`<details class="criterion-summary"><summary>Sintesi AI</summary><p>${e(result.reason)}</p>${extra.map(q=>`<blockquote>${e(q)}</blockquote>`).join('')}</details>`:''}
  </details>`;
}
