import {e,num,euro,stamp,safeUrl,selectOptions} from './utils.js';

export function quoteTable(q){
  const url=safeUrl(q.source_url);
  return `<div class="omi-provenance"><strong>${e(q.source_label)}</strong><span>${e(q.period)} · Zona ${e(q.zone_code)}</span>${url?`<a href="${e(url)}" target="_blank" rel="noopener noreferrer">Tabella ufficiale ↗</a>`:'<span>Fonte non collegata</span>'}</div><div class="omi-quote-list">${q.rows.map(r=>`<article class="omi-quote-row"><div><strong>${e(r.type)}</strong><span>${e(r.condition)}</span></div><div><strong>${num(r.min_sqm,2)} – ${num(r.max_sqm,2)}</strong><span>EUR / m²</span></div><div><span>Superficie</span><strong>${r.area_basis==='gross'?'Lorda':r.area_basis==='net'?'Netta':'Non indicata'}</strong></div></article>`).join('')}</div><p class="small muted">Fascia di zona, non perizia. ${q.retrieved_at?'Consultata '+stamp(q.retrieved_at,true)+'.':'Data di consultazione non disponibile.'}</p>`;
}

export function marketContext(p){
  const q=p.market_context;
  if(!q?.status)return '';
  if(q.status!=='available')return `<section class="detail-section"><h2>Quotazioni OMI</h2><p>${e(q.reason)}</p></section>`;
  return `<section class="detail-section"><details><summary>Tabella OMI e metodo</summary><p><strong>${e(q.zone_label)}</strong></p>${q.location_method||q.boundary_distance_m!=null?`<p class="small muted">${e(q.location_method)}${q.boundary_distance_m!=null?` · Distanza dal confine: ${num(q.boundary_distance_m)} m`:""}</p>`:""}${quoteTable(q)}${q.stale?'<p class="caveat">Periodo non utilizzabile per una stima corrente: aggiorna il riferimento.</p>':q.scenarios?.length?`<details><summary>Ipotesi di valore</summary><p>Ogni riga risponde a un’ipotesi diversa. Il range moltiplica la quotazione OMI per ${num(p.surface)} m² assumendo che la superficie abbia la stessa base. Lo scostamento positivo indica una richiesta sopra il punto medio; non è un rendimento né uno sconto accertato.</p><div class="table-scroll"><table class="benchmark-table"><thead><tr><th>IPOTESI</th><th>RANGE TEORICO</th><th>RICHIESTA / PUNTO MEDIO</th></tr></thead><tbody>${q.scenarios.map(r=>`<tr><td>${e(r.type)} · ${e(r.condition)}<small>Superficie ${r.area_basis==='gross'?'lorda':'netta'} · posizione da confermare</small></td><td>${euro(r.range_min)} – ${euro(r.range_max)}</td><td>${r.delta_midpoint_pct>0?'+':''}${num(r.delta_midpoint_pct)}%</td></tr>`).join('')}</tbody></table></div><p class="muted">Stima condizionata, incertezza non calibrata. Il range OMI non è un intervallo di confidenza. Questi scenari non alimentano score e sconto verificati.</p></details>`:''}</details></section>`;
}

export function omiForm(provinces){
 return `<form id="omi-form" class="modal-form"><div class="form-grid"><label>Provincia<select aria-label="Provincia" id="omi-province" name="province" required><option value="">Seleziona provincia</option>${selectOptions(provinces.map(p=>[p.code,p.name]),'')}</select></label><label>Comune<select aria-label="Comune OMI" id="omi-city" name="city_code" required disabled><option value="">Seleziona prima la provincia</option></select></label><label class="span-2">Zona OMI<select aria-label="Zona OMI" id="omi-zone" name="zone" required disabled><option value="">Seleziona prima il comune</option></select></label><label>Destinazione<select aria-label="Destinazione OMI" name="usage">${selectOptions([['R','Residenziale'],['C','Commerciale'],['T','Terziaria'],['P','Produttiva']],'R')}</select></label></div><input type="hidden" name="period" id="omi-period"><div class="omi-consult-actions"><button class="btn primary" type="submit" id="omi-submit" disabled>Consulta quotazioni</button><p id="omi-status" role="status"></p></div><div id="modal-error" class="form-error" role="alert"></div><button type="button" class="btn" data-action="omi-retry" id="omi-retry" hidden>Riprova</button><div id="omi-result" aria-live="polite"></div></form>`;
}
