import {catalogView,catalogPlaceholder} from './catalog-ui.js';
import {action,badge,empty,notice,pageHeading,propertyThumb} from './ui.js';
import {liveOverview} from './overview.js';
import {insightsView} from './insights.js';
import {pipelineView,inboxView,marketView,savedViewBar,operationsSettings,duplicateControls,stages} from './product-ui.js';
import {icon,mark} from './icons.js';
import {e,label,reviewLabel,num,euro, amount,relative,stamp,initials,activeRun,tone,strategyTags,score,discount,selectOptions} from './utils.js';

export const pages = {
  overview:['grid','Panoramica'], properties:['building','Opportunità'], pipeline:['board','Pipeline'], agents:['agent','Agenti AI'],
  sources:['layers','Fonti e importazioni'], market:['chart','Benchmark'], insights:['chart','Insight'], quality:['quality','Qualità dati'], inbox:['bell','Inbox'], activity:['pulse','Attività'], settings:['settings','Impostazioni'],
};
export {badge,empty,notice,pageHeading} from './ui.js';
export function sourceMode() { return false; }
export function shownAgents(s) {return s.data.agents;}
export function shownSources(s) {return s.data.sources;}

export function loginView() {
  return `<div class="login-layout">
    <section class="login-story"><a class="brand light" href="/">${mark}<span>vedra<span class="brand-dot">.</span></span></a>
      <div class="story-copy"><span class="eyebrow">REAL ESTATE INTELLIGENCE</span><h1>Il prossimo deal.<br>Una visione<br><em>più chiara.</em></h1><p>Un workspace per trovare, confrontare e mettere a fuoco le opportunità immobiliari.</p></div>
      <div class="story-architecture" aria-hidden="true"><div class="arch-building a"></div><div class="arch-building b"></div><div class="arch-building c"></div><div class="arch-ground"></div></div>
      <div class="story-footer"><span>Origination. Screening. Decisioni informate.</span><span>PRIVATE WORKSPACE</span></div>
    </section>
    <main class="login-panel" id="main"><div class="login-box"><span class="tiny-icon">${icon('lock')}</span><div class="eyebrow">IL TUO WORKSPACE</div><h2>Bentornato.</h2><p>Accedi per gestire agenti e opportunità.</p>
      <form id="login-form"><label>Email<input name="email" type="email" autocomplete="username" required placeholder="nome@azienda.it"></label><label>Password<div class="password-wrap"><input name="password" type="password" autocomplete="current-password" required placeholder="La tua password">${action('show-password','', 'eye','icon-button','type="button" aria-label="Mostra password"')}</div></label><div class="form-error" id="login-error" role="alert"></div><button type="submit" class="btn primary full">Accedi al workspace ${icon('arrow')}</button></form>
      <div class="login-hint">Al primo avvio le credenziali sono generate dallo script di setup. Nessun account pubblico o password condivisa.</div><div class="login-footnote">${icon('quality')} Accesso riservato · Dati e permessi sotto controllo</div>
    </div><span class="version">Vedra · Workspace privato</span></main>
  </div>`;
}

export function shell(s) {
  const user=s.user, editor=user.role!=='viewer';
  const selected=pages[s.page] || pages.overview;
  return `<div class="workspace ${s.mobileNav?'nav-open':''}">
    <aside class="sidebar"><a class="brand" href="#overview">${mark}<span>vedra<span class="brand-dot">.</span></span></a>
      <div class="workspace-switch"><span class="workspace-initial">RE</span><div><strong>${e(s.ops?.workspace?.name||"Investment workspace")}</strong><span>Real Estate · Workspace</span></div><span class="little-lock">${icon('lock')}</span></div>
      <div class="nav-label">WORKSPACE</div><nav aria-label="Navigazione principale">${Object.entries(pages).filter(([key])=>key!=='settings').map(([key,[ic,text]])=>`<a href="#${key}" class="nav-link ${s.page===key?'active':''}" ${s.page===key?'aria-current="page"':''}>${icon(ic)}<span>${text}</span>${key==='properties'?`<span class="nav-count">${num(s.data.stats.real_count)}</span>`:''}</a>`).join('')}</nav>
      <div class="sidebar-spacer"></div><div class="engine-card"><div class="engine-symbol">${icon('agent')}</div><div><strong>${s.data.runtime.ai_configured?'AI configurata':s.data.runtime.hermes_configured?'Hermes configurato':'Runtime regole'}</strong><span>${s.data.runtime.ai_configured?e(s.data.runtime.ai_model):'Workflow verticale · AI opzionale'}</span></div><span class="status-dot ${s.ops?.worker?.healthy?'green':''}"></span></div>
      <a href="#settings" class="nav-link ${s.page==='settings'?'active':''}">${icon('settings')}<span>Impostazioni</span></a>
      <div class="profile"><span class="avatar">${e(initials(user.name))}</span><div><strong>${e(user.name)}</strong><span>${e({admin:'Amministratore',analyst:'Analista',viewer:'Sola lettura'}[user.role])}</span></div>${action('logout','', 'logout','icon-button','aria-label="Esci dal workspace" title="Esci"')}</div>
    </aside>
    <button class="nav-scrim" data-action="mobile-menu" aria-label="Chiudi navigazione"></button>
    <div class="workspace-main"><header class="topbar"><div class="breadcrumb">${action('mobile-menu','', 'menu','icon-button mobile-only','aria-label="Apri navigazione"')}<span class="breadcrumb-home">Workspace</span>${icon('chevron')}<strong>${e(selected[1])}</strong></div><div class="topbar-actions"><form id="global-search" class="global-search">${icon('search')}<input id="global-query" name="q" aria-label="Cerca immobili" placeholder="Cerca immobili, zone, opportunità…" value="${e(s.filters.q)}"><button type="submit" class="icon-button" aria-label="Cerca">${icon('arrow')}</button></form><a href="#inbox" class="icon-button inbox-shortcut" aria-label="Apri notifiche">${icon('bell')}${s.ops?.unread?'<span class="notification-indicator"></span>':''}</a>${action('refresh','', 'refresh',`icon-button ${s.busy?'rotating':''}`,'aria-label="Aggiorna dati" title="Aggiorna dati"')}${action('theme','',document.documentElement.dataset.theme==='dark'?'sun':'moon','icon-button','aria-label="Cambia tema" title="Cambia tema"')}<span class="header-divider"></span><span class="header-avatar">${e(initials(user.name))}</span></div></header>
      <main class="main-content" id="main"><div id="page">${s.data.has_more&&s.page!=='properties'?'<div class="notice warning">Questa sintesi usa fino a 2.000 annunci. Opportunità e Insight interrogano l’intero archivio.</div>':''}${renderPage(s)}</div><footer class="workspace-footer"><span>VEDRA <span class="dot-separator">/</span> REAL ESTATE INTELLIGENCE</span><span>Screening preliminare, non una perizia · Aggiornato ${stamp(s.data.server_time)}</span></footer></main>
    </div>
  </div>`;
}

export function renderPage(s) {
  return ({overview:liveOverview,insights:insightsView,pipeline:pipelineView,inbox:inboxView,market:marketView,properties:propertiesView,agents:agentsView,sources:sourcesView,quality:qualityView,activity:activityView,settings:settingsView}[s.page] || liveOverview)(s);
}
function metric(title,value,detail,ico,extra='') {
  return `<section class="metric-card ${extra}"><div class="metric-label">${e(title)}<span class="metric-icon">${icon(ico)}</span></div><div class="metric-value">${value}</div><div class="metric-detail">${detail}</div></section>`;
}
function tableRows(s, rows, selectable=false) {
  return rows.map(p=>`<tr data-property-row="${e(p.id)}">${selectable?`<td class="check-cell"><input type="checkbox" id="select-${e(p.id)}" data-select-property="${e(p.id)}" ${s.selected.has(p.id)?'checked':''} aria-label="Seleziona ${e(p.title)}"></td>`:''}<td class="property-cell"><button class="property-link" data-action="property" data-id="${e(p.id)}"><span class="property-mini type-${e(p.property_type)}">${icon('building')}</span><span><strong>${e(p.title)}</strong><span class="property-location">${e(p.city)} · ${e(p.zone || 'Zona non disponibile')} </span></span></button></td><td>${score(p)}</td><td class="numeric"><strong>${amount(p.price,p.currency)}</strong><small>${p.surface==null?'Superficie n.d.':num(p.surface)+' m²'}</small></td><td class="numeric">${amount(p.price_sqm,p.currency)}<small>per m²</small></td><td>${discount(p)}<small>vs riferimento</small></td><td><div class="strategy-group">${strategyTags(p,2)}</div></td><td class="right"><button class="icon-button star-button ${p.starred?'selected':''}" data-action="star" data-id="${e(p.id)}" aria-label="${p.starred?'Rimuovi':'Aggiungi'} preferito" ${s.user.role==='viewer'?'disabled':''}>${icon('star')}</button></td></tr>`).join('');
}
function table(s, rows, selectable=false) {
  if (!rows.length) return empty('Nessuna opportunità in questa vista','Modifica i filtri oppure acquisisci il primo campione di dati.');
  return `<div class="table-scroll"><table class="properties-table"><thead><tr>${selectable?'<th class="check-cell"><span class="sr-only">Confronta</span></th>':''}<th>IMMOBILE</th><th>SCORE ${icon('info')}</th><th class="numeric">PREZZO / SUPERFICIE</th><th class="numeric">PREZZO AL M²</th><th>DELTA ZONA</th><th>STRATEGIA</th><th><span class="sr-only">Preferito</span></th></tr></thead><tbody>${tableRows(s,rows,selectable)}</tbody></table></div>`;
}
export function propertyResults(s) {
  if(s.catalog){const placeholder=catalogPlaceholder(s);if(placeholder)return placeholder;}
  const rows=s.catalog.items;
  if(s.layout==='grid')return rows.length?`<div class="property-grid">${rows.map(p=>`<article class="property-card"><div class="property-art type-${e(p.property_type)}"><label class="card-select"><input type="checkbox" id="select-${e(p.id)}" data-select-property="${e(p.id)}" ${s.selected.has(p.id)?'checked':''} aria-label="Seleziona ${e(p.title)}"><span>Seleziona</span></label>${propertyThumb(p,'card-thumb')}<button class="icon-button star-button ${p.starred?'selected':''}" data-action="star" data-id="${e(p.id)}" aria-label="Preferito" ${s.user.role==='viewer'?'disabled':''}>${icon('star')}</button></div><div class="property-card-body"><div class="property-card-place">${icon('pin')}${e(p.city)} · ${e(p.zone)}</div><button class="card-title" data-action="property" data-id="${e(p.id)}">${e(p.title)}</button><div class="property-card-price"><strong>${amount(p.price,p.currency)}</strong><span>${num(p.surface)} m²</span></div><div class="strategy-group">${strategyTags(p)}</div><div class="property-card-bottom">${score(p)}<span>Score preliminare</span>${discount(p)}<button class="icon-button" data-action="property" data-id="${e(p.id)}" aria-label="Apri scheda">${icon('arrow')}</button></div></div></article>`).join('')}</div>`:empty('Nessun immobile corrisponde ai filtri','Prova ad allargare la ricerca.');
  return table(s,rows,true);
}
export function propertiesView(s) {
  return catalogView(s,propertyResults(s),savedViewBar(s));
}

export function agentsView(s) {
  const agents=shownAgents(s), canEdit=s.user.role!=='viewer';
  return `${pageHeading('AGENT CONTROL','Ricerche che non ripartono da zero.','Configura i criteri, scegli le fonti e controlla ogni esecuzione.',canEdit?action('new-agent','Crea agente','plus','btn primary'):'')}
    ${notice('Ogni agente conserva criteri, fonti e risultati. Con la ricerca online, Hermes cerca e seleziona gli annunci; Vedra verifica e salva i dati della fonte.')}
    <div class="agent-grid">${agents.map((a,i)=>`<article class="agent-card"><div class="agent-card-head"><span class="agent-symbol large variation-${i%3}">${icon('agent')}</span>${badge(activeRun(a.last_run)?label(a.last_run.status):a.active?'Attivo':'In pausa',a.active?'success':'neutral')}<button class="icon-button" data-action="edit-agent" data-id="${e(a.id)}" aria-label="Configura ${e(a.name)}">${icon(canEdit?'edit':'eye')}</button></div><div class="agent-card-title"><h2>${e(a.name)}</h2><span>${icon('pin')} ${e(a.city)} </span></div><div class="agent-criteria"><div><span>Budget</span><strong>${a.criteria.min_price?`${euro(a.criteria.min_price,true)} – `:"Fino a "}${euro(a.criteria.max_price,true)}</strong></div><div><span>Superficie minima</span><strong>${num(a.criteria.min_surface)} m²</strong></div><div><span>Strategia</span><strong>${a.criteria.strategies.length?a.criteria.strategies.map(label).join(', '):'Tutte'}</strong></div><div><span>Frequenza</span><strong>${a.interval_minutes?`Ogni ${num(a.interval_minutes)} min`:'Manuale'}</strong></div></div><div class="agent-outcomes"><div><strong>${num(a.total)}</strong><span>Acquisiti</span></div><button class="stat-button" data-action="agent-results" data-id="${e(a.id)}"><strong>${num(a.qualified)}</strong><span>Nei criteri ${icon('arrow')}</span></button><span class="runtime-label ${a.runtime==='hermes'?'hermes':''}">${icon(a.runtime==='hermes'?'spark':'code')} ${a.runtime==='hermes'?'Hermes':a.runtime==='llm'?'AI verticale':'Regole'}</span></div><div class="agent-schedule">${icon('clock')}<span>${a.last_run?`Ultimo run ${relative(a.last_run.finished_at||a.last_run.created_at)}`:'Nessun run'}${a.next_run&&a.active?` · Prossimo ${relative(a.next_run)}`:''}</span></div><div class="agent-actions">${canEdit?`${action('run-agent',activeRun(a.last_run)?'Mostra esecuzione':'Esegui ora',activeRun(a.last_run)?'pulse':'play','btn primary',`data-id="${e(a.id)}"`)}${action('toggle-agent',a.active?'Pausa':'Riprendi',a.active?'pause':'play','btn',`data-id="${e(a.id)}"`)}`:''}${action('agent-readiness','Diagnostica','quality','btn small-btn',`data-id="${e(a.id)}"`)}${a.last_run?action('run-detail','','list','icon-button',`data-id="${e(a.last_run.id)}" aria-label="Log dell’ultimo run"`):''}</div></article>`).join('')}${canEdit?`<button class="new-agent-card" data-action="new-agent"><span>${icon('plus')}</span><strong>Un’altra prospettiva sul mercato.</strong><p>Aggiungi una zona o una strategia di ricerca.</p><span class="text-link">Crea un agente ${icon('arrow')}</span></button>`:''}</div>`;
}

export function sourcesView(s) {
  const sources=shownSources(s), admin=s.user.role==='admin';
  return `${pageHeading('DATA ACQUISITION','Fonti','Ogni fonte ha un metodo, un permesso documentato e uno stato osservabile.',admin?action('import','Importa dati','upload','btn')+action('new-source','Collega fonte HTML','plus','btn primary'):'')}
    ${notice('<strong>Nessun portale è preautorizzato.</strong> Il connettore legge HTML/JSON-LD e selettori configurati, con browser opzionale. Il dominio deve essere consentito sul server. CAPTCHA, divieti robots e blocchi fermano la raccolta.','warning')}
    <div class="source-grid">${sources.map(src=>`<article class="panel source-card"><div class="source-top"><span class="source-symbol">${icon(src.kind==='import'?'upload':'link')}</span><div><h2>${e(src.name)}</h2><span class="muted small">${e(src.domain || label(src.kind))}</span></div>${badge(src.enabled?label(src.status):'Disabilitata',src.enabled?tone(src.status):'neutral')}</div><div class="source-method"><span>${e(label(src.kind))}</span>${src.kind==='html'&&!src.allowed_on_server?'<span class="badge warning">Dominio non in allowlist</span>':''}</div><div class="source-metrics"><div><strong>${num(src.property_count)}</strong><span>Immobili acquisiti</span></div><div><strong>${num(src.quality)}<small>%</small></strong><span>Campi presenti</span></div><div><strong class="text-metric">${src.kind==='html'?(src.config.render_js?'Browser':'HTTP'):'Locale'}</strong><span>Metodo di accesso</span></div></div>${src.last_error?`<div class="inline-error">${e(src.last_error)}</div>`:''}<div class="source-bottom"><span>${src.last_checked?`Verificata ${relative(src.last_checked)}`:'Non ancora verificata in rete'}</span>${admin?`<div>${src.kind==='html'?action('edit-source','Configura','edit','btn small-btn',`data-id="${e(src.id)}"`):''}${action('probe-source','Test','pulse','btn small-btn',`data-id="${e(src.id)}"`)}${action('toggle-source','',''+(src.enabled?'pause':'play'),'icon-button',`data-id="${e(src.id)}" aria-label="${src.enabled?'Disabilita':'Abilita'} fonte"`)}</div>`:''}</div></article>`).join('') || empty('Nessuna fonte reale collegata','Aggiungi una fonte autorizzata o importa un campione CSV / HTML del cliente.')}</div>
    <section class="panel import-callout"><span class="import-big-icon">${icon('database')}</span><div><h2>Parti dai dati che hai già.</h2><p>CSV immobili, HTML di un annuncio oppure benchmark in formato normalizzato. Ogni importazione mantiene la provenienza del dato.</p><div class="import-formats"><span>CSV / UTF-8</span><span>HTML / JSON-LD</span><span>BENCHMARK / CSV</span></div></div>${admin?action('import','Apri importazione','upload','btn primary'):''}</section>`;
}

export function qualityView(s) {
  const d=s.data, without=d.properties.filter(p=>p.score==null).length;
  return `${pageHeading('DATA OBSERVABILITY','Qualità dei dati','Misuriamo la presenza dei campi e mostriamo le lacune, senza scambiarle per precisione.')}
    <div class="metrics-grid">${metric('Completezza media',`${num(d.stats.quality,1)}<span class="value-unit">%</span>`,'10 campi controllati per immobile','quality')}${metric('Campione osservato',num(d.stats.properties),'Annunci nella lista corrente','building')}${metric('Senza score',num(without),'Benchmark o dati non sufficienti','info')}${metric('Possibili duplicati',num(d.duplicates.length),'Da verificare, mai uniti automaticamente','layers')}</div>
    <div class="quality-layout"><section class="panel coverage-panel"><div class="panel-label">FIELD COVERAGE</div><h2>La disponibilità, campo per campo.</h2><p class="panel-subtitle">Un campo presente può comunque essere inesatto: serve una verifica campionaria.</p><div class="coverage-list">${d.coverage.map(c=>`<div class="coverage-row"><span>${e(label(c.field))}</span><div class="coverage-track"><span class="${c.percent<70?'low':''}" style="width:${c.percent}%"></span></div><strong>${num(c.percent,1)}%</strong><small>${c.present} / ${c.total}</small></div>`).join('')}</div></section><section class="panel quality-notes"><div class="panel-label">REGOLE DI TRASPARENZA</div><h2>Nessun dato inventato.</h2>${[
      ['check','Campi mancanti espliciti','Prezzo, metratura o indirizzo assenti rimangono non disponibili. Non sono completati dal modello.'],
      ['layers','Benchmark compatibili','Comune, zona, tipologia, stato, base della superficie e periodo devono essere confrontabili.'],
      ['document','Evidenza per ogni strategia','Le citazioni di Hermes devono comparire davvero nella descrizione acquisita.'],
      ['clock','Storico osservato, non stimato','La prima rilevazione non equivale alla data di pubblicazione o al tempo di vendita.'],
    ].map(([ic,t,p])=>`<div class="quality-principle"><span>${icon(ic)}</span><div><h3>${t}</h3><p>${p}</p></div></div>`).join('')}</section></div>
    <section class="panel"><div class="table-panel-heading"><div><div class="panel-label">REVISIONE UMANA</div><h2>Possibili duplicati</h2></div><span class="quiet-pill">Matching conservativo</span></div>${d.duplicates.length?`<div class="duplicate-list">${d.duplicates.map(x=>{const a=d.properties.find(p=>p.id===x.a),b=d.properties.find(p=>p.id===x.b);return `<div><button data-action="property" data-id="${e(x.a)}">${e(a?.title)}</button>${icon('link')}<button data-action="property" data-id="${e(x.b)}">${e(b?.title)}</button><span class="small muted">${e(x.reason || 'Stesso indirizzo e superficie simile')}</span>${duplicateControls(s,x)}</div>`;}).join('')}</div>`:empty('Nessuna coppia da segnalare','Vengono confrontati indirizzo, comune, tipo e superficie tra fonti diverse. Nessuna deduplica fotografica avanzata in questa preview.')}</section>`;
}

export function activityView(s) {
  return `${pageHeading('OPERATIONS','Esecuzioni','Esecuzioni, errori e risultati: ciò che è successo, non ciò che il sistema avrebbe dovuto fare.')}
    <section class="panel activity-panel">${s.data.runs.length?`<div class="table-scroll"><table class="activity-table"><thead><tr><th>AGENTE / ESECUZIONE</th><th>STATO</th><th>RUNTIME</th><th>ACQUISITI</th><th>NUOVI</th><th>ERRORI</th><th>AVVIO</th><th></th></tr></thead><tbody>${s.data.runs.map(r=>`<tr><td><button class="plain-link" data-action="run-detail" data-id="${e(r.id)}">${e(r.agent_name)}</button><small>${e(r.id.slice(0,8))} · ${e({manual:'avvio manuale',schedule:'programmata',external:'trigger esterno'}[r.trigger] || r.trigger)}</small></td><td>${badge(label(r.status),tone(r.status))}</td><td><span class="runtime-label">${icon(r.runtime==='hermes'?'spark':'code')}${r.runtime==='hermes'?'Hermes':r.runtime==='llm'?'AI verticale':'Regole'}</span></td><td>${num(r.stats.processed||0)}</td><td>${num(r.stats.new||0)}</td><td class="${r.stats.errors?'danger-text':''}">${num(r.stats.errors||0)}</td><td>${stamp(r.created_at)}</td><td>${action('run-detail','','chevron','icon-button',`data-id="${e(r.id)}" aria-label="Dettagli run"`)}</td></tr>`).join('')}</tbody></table></div>`:empty('Nessuna esecuzione','Crea un agente e avvia il primo run dalla dashboard.')}</section>`;
}

export function settingsView(s) {
  const admin=s.user.role==='admin';
  return `${pageHeading('WORKSPACE SETTINGS','Impostazioni','Il workspace è privato. Credenziali e permessi di rete restano sul server.')}
    <div class="settings-grid"><section class="panel settings-panel"><span class="setting-icon">${icon('agent')}</span><h2>Modello AI & Hermes</h2><p>Scegli il modello dal server. Il motore verticale usa Chat Completions; Hermes rimane un’integrazione alternativa e privata.</p><div class="setting-status">${badge((s.data.runtime.ai_configured||s.data.runtime.hermes_configured)?'Configurato':'Non configurato',(s.data.runtime.ai_configured||s.data.runtime.hermes_configured)?'success':'neutral')}</div><div class="code-config">AI_API_BASE_URL<br>AI_API_KEY<br>AI_MODEL</div><p class="small">${s.data.runtime.ai_configured?"Modello configurato: "+e(s.data.runtime.ai_model):"Nessun modello configurato. Il runtime Regole è disponibile senza AI."}</p><p class="small">Configura <code>.env</code> e riavvia il servizio. Le skills servono solo a Hermes. Con Regole locali non viene chiamato un LLM.</p>${admin?action('runtime-test','Verifica Hermes','pulse','btn primary'):''}<div id="runtime-result"></div></section>
    <section class="panel settings-panel"><span class="setting-icon">${icon('quality')}</span><h2>Accesso ai dati</h2><p>Ogni dominio deve essere inserito in <code>LIVE_ALLOWED_DOMAINS</code>. Il permesso della fonte viene registrato nella sua configurazione.</p><dl class="settings-facts"><div><dt>Browser opzionale</dt><dd>${s.data.runtime.browser_enabled?'Abilitato':'Disabilitato'}</dd></div><div><dt>Scheduler del workspace</dt><dd>${s.data.runtime.scheduler_enabled?'Attivo':'Disattivato'}</dd></div><div><dt>Persistenza</dt><dd>${s.data.runtime.database==='postgres'?'PostgreSQL':'SQLite'} + snapshot locali</dd></div><div><dt>Ambito</dt><dd>Singolo workspace privato</dd></div></dl><p class="small">Per usare il cron di Hermes come trigger esterno, imposta la ricerca su Manuale: un solo scheduler deve avviare il lavoro.</p></section>
    ${operationsSettings(s)}${admin?`<section class="panel settings-panel full-settings"><div class="table-panel-heading"><div><div class="panel-label">TEAM ACCESS</div><h2>Team</h2></div>${action('new-user','Invita un utente','plus','btn')}</div><p class="small muted">Crea un account con password iniziale. Nessuna email viene inviata automaticamente.</p><div id="users-list">${s.users?`<div class="users-list">${s.users.map(u=>`<div class="user-row"><span class="avatar">${e(initials(u.name))}</span><div><strong>${e(u.name)}</strong><small>${e(u.email)}</small></div><span class="quiet-pill">${e(u.role)}</span></div>`).join('')}</div>`:'<div class="loading-line">Caricamento utenti…</div>'}</div></section>`:''}</div>`;
}
